#!/bin/bash

#############
# AutoStart #
#############

#SXHKD
pgrep -x sxhkd > /dev/null || sxhkd &
#Wallpaper
feh --bg-fill ~/.wallpaper.png &
#Bar
~/.config/polybar/launch.sh &
#Compositor
picom &
#Applets
nm-applet --no-agent &
#Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
#GreenClip
greenclip daemon &

########
# BSPC #
########

#Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9
#Borders and gaps
bspc config border_width         0
bspc config window_gap          15
bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true
bspc config automatic_scheme	spiral
#SelectionColor
bspc config presel_feedback_color "fd2e59"
#Mouse
bspc config focus_follows_pointer true
bspc config pointer_modifier	super
xsetroot -cursor_name left_ptr &
#States
bspc rule -a mpv state=fullscreen
